version: "3"
services:
 pihole:
  image: pihole/pihole:latest
  container_name: pihole
  restart: unless-stopped
  volumes:
   - /mnt/pihole/pihole/:/etc/pihole/
   - /mnt/pihole/dnsmasq.d/:/etc/dnsmasq.d/
  network_mode: host
#  ports:
#   - 53:53/tcp
#   - 53:53/udp
#   - 67:67/udp
#   - 80:80/tcp
#   - 443:443/tcp
  dns:
   - 127.0.0.1
   - 1.1.1.1
  cap_add:
   - NET_ADMIN
  environment:
    TZ: 'Europe/Berlin'
    ServerIP: 192.168.2.107
    PROXY_LOCATION: pihole
    VIRTUAL_HOST: pi.hole
    WEBPORT: 5089